unstable_features = true
imports_granularity = "crate"
group_imports = "StdExternalCrate"
normalize_comments = true
reorder_impl_items = true
use_field_init_shorthand = true
wrap_comments = true
format_code_in_doc_comments = true
match_block_trailing_comma = true
overflow_delimited_expr = true
