// MIT LICENSE
//
// Copyright (c) 2017-2020 Bernhard Schuster
// Copyright (c) 2015 Storeness UG (haftungsbeschraenkt)
//
// Permission is hereby granted, free of charge, to any person obtaining a copy
// of this software and associated documentation files (the "Software"), to deal
// in the Software without restriction, including without limitation the rights
// to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
// copies of the Software, and to permit persons to whom the Software is
// furnished to do so, subject to the following conditions:
//
// The above copyright notice and this permission notice shall be included in
// all copies or substantial portions of the Software.
//
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
// AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
// LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
// OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
// THE SOFTWARE.

//! Copied from: <https://github.com/spearow/juice/blob/2fb447db8f6c8166b2026e74013d57227062fcb3/juice/src/capnp_util.rs>

pub trait CapnpWrite<'a> {
    /// The Builder that was autogenerated by capnp.
    type Builder;

    /// Write the struct into the message that is being built by the Builder.
    fn write_capnp(&self, builder: &mut Self::Builder);
}

pub trait CapnpRead<'a> {
    /// The Reader that was autogenerated by capnp.
    type Reader;

    /// Read the struct from the Reader.
    fn read_capnp(reader: Self::Reader) -> Self;
}
