[package]
name = "rast-cli"
version = "0.1.0"
edition = "2021"
authors = ["Marek 'seqre' Grzelak <marek.grzelak@seqre.dev>"]
description = "Agent library for Rast C2 & RAT framework."
readme = "README.md"
repository = "https://github.com/seqre/rast"
license = "GPL-3.0-or-later"
keywords = ["c2", "rat", "cli"]
publish = false

[dependencies]
rast = { path = "../rast" }
tokio = { workspace = true, features = ["rt"] }
tokio-util = { workspace = true, features = ["codec"] }
anyhow = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
futures-util = { workspace = true }
bytes = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }

crossterm = { version = "0.25" }
shellfish = { version = "0.7", default-features = true, features = [ "async", "tokio" ]}
