server:
  agent_listeners:
    - tcp:
        ip: &ip 127.0.0.1
        port: 42069
    - quic:
        ip: *ip
        port: 42071
        server_name: &name rast-c2

  ui_listeners:
    - tcp:
        ip: *ip
        port: 42070

agent:
  connections:
    - tcp:
        ip: *ip
        port: 42069
    - quic:
        ip: *ip
        port: 42071
        server_name: *name
